### ISSUE TITLE
Worksheet: "Print" does not display/print partial results

### ISSUE THREAD

**Issue by ramonski** [senaite/bika.lims#288]
## Steps to reproduce

- Create 2 new ARs and receive the Samples
- Create a new Worksheet and add all Analyses of these ARs to the worksheet
- Add results for the one of the two ARs (half of the Analyses) and submit the results for verification
- Press the "Print" button

## Current behavior

No results are displayed on the report

## Expected behavior

Partial results are added to the report

## Screenshot (optional)

<img width="1159" alt="ws17-0001_ _liscon_lims" src="https://user-images.githubusercontent.com/713193/31902030-b357c272-b823-11e7-9d00-b16a712bad8f.png">

<img width="832" alt="localhost_8081_senaite_worksheets_ws17-0001_print" src="https://user-images.githubusercontent.com/713193/31902125-0c907ff0-b824-11e7-82df-864f87b436aa.png">

**Comment by xispa** [comment]
I see. The aim of this form is to allow the analyst to introduce results manually by hand (maybe he/she is not in the lab or there isn't any pc available on place) and later retype the results when a pc is available. So, we assumed this report is used before the introduction of any result. But totally agree, the report should display partial results, cause maybe the analyst needs some previous results to fill the report manually. 

I suggest to make a distinction in the form itself depending on the analysis status. If the result is for an analysis that have been validated, then the result should be displayed more prominently (or 'as is'). If the result is for an analysis that haven't been yet verified, I'd add an start next to the result (in red color) and a prominent statement at the bottom in red too, something like "Provisional result, verification pending".

**Comment by ramonski** [comment]
Good point and we agree on that. I will start working on that now.
