### ISSUE TITLE
Publish view does not return Analyses in the right order

### ISSUE THREAD

**Issue by ramonski** [senaite/bika.lims#290]
## Steps to reproduce

1. Create a new AR with Analyses Services which contain a "Sort Key"
2. Publish the results

## Current behavior

Analyses within a category are not sorted in the right order

## Expected behavior

Analyses are sorted according to their sort key like in the AR view.

I _think_ this is because the analyses are processed in a dictionary in `bika/lims/analysisrequest/publish.py`

## Screenshot (optional)

--

**Comment by xispa** [comment]
Fixed in https://github.com/senaite/bika.lims/pull/333
