### ISSUE TITLE
Worksheet: Positions row overflows result in incorrect markup

### ISSUE THREAD

**Issue by ramonski** [senaite/bika.lims#302]
## Steps to reproduce

Create a new Worksheet and add about 10 Analyses per position 

## Current behavior

The rows after the "Position box" flush on the left hand side

## Expected behavior

The rows should be rendered correctly

## Screenshot (optional)

<img width="1141" alt="ws17-0004" src="https://user-images.githubusercontent.com/713193/31989751-7d6f8ff4-b973-11e7-883e-0c1f07ea4001.png">

**Comment by xispa** [comment]
I've done some checks and I'd say https://github.com/senaite/bika.lims/pull/331 fixes this issue
