### ISSUE TITLE
Images are not printed on final report

### ISSUE THREAD

**Issue by ramonski** [senaite/bika.lims#328]
## Steps to reproduce

Publish an AR and click the "Print" Button

## Current behavior

Images are missing

## Expected behavior

Images (Accreditation Stars, Attachments etc.) are printed to the report

## Notes

This might be related #326 (likely) or the changed workflow settings and how WeasyPrint fetches the Images: `bika.lims.utils.bika_url_fetcher`.

**Comment by juangallostra** [comment]
#348 solves this by adding ```Attachment``` to ```portal_catalog```.
