### ISSUE TITLE
Traceback if Analyses get added to an AR over "Manage Analyses" View

### ISSUE THREAD

**Issue by ramonski** [senaite/bika.lims#354]
## Steps to reproduce

- Create a new AR
- Add Analyses over "Manage Analyses" view
- Click the "Save" button (button is also flaky and appears not always)

## Current behavior

Traceback occurs

## Expected behavior

Analyses are added

## Traceback

```
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module bika.lims.browser.analysisrequest.workflow, line 59, in __call__
  Module bika.lims.browser.analysisrequest.workflow, line 233, in workflow_action_save_analyses_button
  Module Products.Archetypes.BaseFolder, line 166, in __getitem__
  Module OFS.ObjectManager, line 783, in __getitem__
KeyError: ''
```

**Comment by grulisco** [comment]
When adding an AS:

![grafik](https://user-images.githubusercontent.com/25460329/32414592-d18fe89e-c22a-11e7-9b10-342bdea4e3b6.png)

Traceback Error after save:

Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module bika.lims.browser.analysisrequest.workflow, line 59, in __call__
  Module bika.lims.browser.analysisrequest.workflow, line 233, in workflow_action_save_analyses_button
  Module Products.Archetypes.BaseFolder, line 166, in __getitem__
  Module OFS.ObjectManager, line 783, in __getitem__
KeyError: ''

**Comment by grulisco** [comment]
In my example the save button does not appear when selecting any AS in addition, except if is in the same AS category. It sometimes appears after the second click on an AS. I see no consisten behaviour...

**Comment by grulisco** [comment]
This occurs with ARs created with testservices for calculation tests.
With some other services defined initially there seems no problem with it.

**Comment by grulisco** [comment]
OK in senaite 1.1.6
