### ISSUE TITLE
Listing Tables: Columns not selectable/deselectable

### ISSUE THREAD

**Issue by grulisco** [senaite/bika.lims#360]
![grafik](https://user-images.githubusercontent.com/25460329/32465793-05a814e2-c345-11e7-94bc-b7d583c174e4.png)

**Comment by xispa** [comment]
@ramonski , could be this something related with senaite.lims rather than with bl?

**Comment by ramonski** [comment]
Indeed, that might be.
@grulisco does this issue also happen on your current test server?

**Comment by ramonski** [comment]
Ok, I just verified that it also happens w/o the `senaite.lims` UI. I also tested directly on the instance so w/o any cache proxy or load balancer in front

**Comment by grulisco** [comment]
@ramonski it happens on test server, of course, as this is the one I'm working on:)

**Comment by grulisco** [comment]
still a problem with senaite 1.1.6
