### ISSUE TITLE
CCEmails are nowhere used to send Emails out of the LIMS

### ISSUE THREAD

**Issue by ramonski** [senaite/bika.lims#361]
## Steps to reproduce

- Create a new AR and add some CCEmails (comma separated)
- Publish the report

## Current behavior

Mentioned CC Emails _do not_ get any Email from the system at any time.

## Expected behavior

Mentioned CC Emails do get the publication report via Email

## Screenshot (optional)

<img width="1168" alt="cc-emails" src="https://user-images.githubusercontent.com/713193/32486936-6b5a8348-c3a8-11e7-9cde-6c45ae52542a.png">

**Comment by ramonski** [comment]
Linked `bikalims/bika.lims` issue: https://github.com/bikalims/bika.lims/issues/2292

**Comment by ramonski** [comment]
Relevant PR in `bikalims/bika.lims`: https://github.com/bikalims/bika.lims/pull/2293

**Comment by xispa** [comment]
Fixed in https://github.com/senaite/bika.lims/pull/363
