### ISSUE TITLE
Adding calibration certificates impossible

### ISSUE THREAD

**Issue by grulisco** [senaite/bika.lims#368]
## Steps to reproduce

Create a new instrument.
After that its calibration certificate is noted as expired (because it does not exist yet).

## Current behavior
The button to add a calibration certificate is missing.

BTW when editing existing instruments, certificates are listed, but the add button is still missing.

## Expected behavior
A button to add a calibration certificate shows up.

## Screenshot (optional)
![grafik](https://user-images.githubusercontent.com/25460329/32558240-989d9d70-c4a4-11e7-8f54-22602c58b2d1.png)

**Comment by grulisco** [comment]
still a problem with senaite 1.1.6

**Comment by Nihadness** [comment]
Dear @rockfruit , the commit below, removed adding new calibration certificate possibility: 
https://github.com/Nihadness/bika.lims/commit/1dfc3de11551be13fe01917f93278275ed1cc7e1#diff-448cefc8fe644775ba33d169221a18c3
How would you justify it? :)

**Comment by grulisco** [comment]
With Release 1.1.7 adding a certificate is working.
But there's a new problem, see #442
