### ISSUE TITLE
Selectable methods in Analysis Request -View-, but they aren't in  Analysis Request -Manage Results-

### ISSUE THREAD

**Issue by Espurna** [senaite/bika.lims#381]
## Steps to reproduce

Create an analysis request with analyses that have methods bind to them.

## Current behavior

Inside analysis request object there are two views where the user can introduce results: View and Manage Results.

If analyses inside analysis request can't be performed using methods, methods selector shouldn't appear.

## Expected behavior

If an analysis can't be performed using a method, method field shouldn't be selectable.

## Screenshot (optional)

Analysis Request VIEW

![selection_023](https://user-images.githubusercontent.com/7425587/32945515-076ea44c-cb94-11e7-81e8-99293320b8a0.png)

Analysis Request MANAGE RESULTS

![selection_022](https://user-images.githubusercontent.com/7425587/32945516-078f54b2-cb94-11e7-8d22-47acf9596550.png)

**Comment by xispa** [comment]
@Espurna is this still happening?. Works in my instance.
