### ISSUE TITLE
AR Add fails silently if e.g. the ID of the AR was already taken

### ISSUE THREAD

**Issue by ramonski** [senaite/bika.lims#393]
## Steps to reproduce

Create a new AR which generates the same ID as another AR in the same folder.

## Current behavior

AR Add form fails silently

## Expected behavior

Error message is displayed

**Comment by ramonski** [comment]
Related PR is https://github.com/bikalims/bika.lims/pull/2318

**Comment by xispa** [comment]
Fixed in https://github.com/senaite/bika.lims/pull/399
