### ISSUE TITLE
IDServer doesn't find next correct sequence after flush

### ISSUE THREAD

**Issue by ramonski** [senaite/bika.lims#394]
## Steps to reproduce
* Set sample format ot "{year}-{samplingDate:%m}{samplingDate:%d}{clientId}-{sampleType}-{seq:05d}".
* Create 2 ARs
* Flush the number generator
* Create another AR

 # Current behavior
The last AR seq is 1

## Expected behavior
The last AR seq should be 3

**Comment by ramonski** [comment]
Related Issue: https://github.com/bikalims/bika.lims/issues/2314

**Comment by ramonski** [comment]
Related PR: https://github.com/bikalims/bika.lims/pull/2315

N.B. Sorry, I accidently mixed changes from PR https://github.com/bikalims/bika.lims/pull/2318  into this one. So best the latter one is merged first.

**Comment by xispa** [comment]
Fixed in https://github.com/senaite/bika.lims/pull/398
