### ISSUE TITLE
Calculation referring to additional python module not triggered

### ISSUE THREAD

**Issue by grulisco** [senaite/bika.lims#408]
## Steps to reproduce
Create a calculation that refers to a self-defined function within an additional python module, 
based on e.g. 2 interim fields.
The calculation is verified by the test parameters and test results.
Assign one AS to this calculation.
Create an AR with this AS.

(@ramonski: look at calculation "Test Python Calcs", service "Test-Analysenservice 1" on our testserver)

## Current behavior
When entering interim fields in AR results view the calculation is not triggered.

## Expected behavior
The result shall be calculated.

**Comment by grulisco** [comment]
Just noticed corresponding errors in plone setup:

NameError: name 'floor' is not defined
NameError: name 'poisson95_og' is not defined

It seems that the needed python libraries (e.g. math) are not imported correctly for the real calculations.

**Comment by grulisco** [comment]
Another calculation fails, that contains strings and IF ... ELSE as part of the expression. It worked before and it still works in the calculation test view.
Might be a related to this issue...

**Comment by ramonski** [comment]
Traceback
```
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module bika.lims.browser.calcs, line 394, in __call__
  Module bika.lims.browser.calcs, line 218, in calculate
  Module bika.lims.browser.calcs, line 1, in <module>
NameError: name 'floor' is not defined
```
