### ISSUE TITLE
Click on an Analysis as LabClerk shows "Insufficient Permissions Error" in Popup

### ISSUE THREAD

**Issue by ramonski** [senaite/bika.lims#422]
## Steps to reproduce

- Create a new AR as a Lab Clerk
- Switch to the analyses view, e.g. `/clients/client-1/Water-0001-R01/analyses`
- Click on an analysis title in the listing

## Current behavior

Popup shows "Insufficient Permissions Error"

## Expected behavior

Popup shows the information of the Analysis Service

**Comment by grulisco** [comment]
Same error on my test instance as Lab Manager as well. Maybe duplicate of #383?

**Comment by ramonski** [comment]
Thanks @grulisco for pointing out, this might be indeed related.

**Comment by ramonski** [comment]
Related to #383

**Comment by ramonski** [comment]
Duplicate of #383
