### ISSUE TITLE
AR Publication from Client Listing does not work

### ISSUE THREAD

**Issue by ramonski** [senaite/bika.lims#424]
## Steps to reproduce

- Select some ARs from the Client AR listing table
- Click on the (Pre-)Publish Button 

## Current behavior

- 404 occurs

## Expected behavior

Preview page is rendered

## Screenshot (optional)

<img width="562" alt="myrtle_ _senaite" src="https://user-images.githubusercontent.com/713193/33327134-0cfdaec8-d457-11e7-9af3-0b60a0a38e0d.png">

**Comment by ramonski** [comment]
Please note:

even after the `publish` view is registered for `IClient` as well, the listing returns this message:
<img width="367" alt="" src="https://user-images.githubusercontent.com/713193/33327233-49c091ae-d457-11e7-9349-2605482879c5.png">

**Comment by xispa** [comment]
Worked in my instance... Only happens in Client AR lists? Can you check if `bika.lims.analysisrequest.default_arreport_template` is registered in `portal_registry` and has a valid value (`default.pt` by default).

**Comment by ramonski** [comment]
Yes, only happens in Client AR lists. Screenshot above is from the fresh installed https://senaite.ridingbytes.com, but I'll check again.

**Comment by ramonski** [comment]
Verified on a fresh installation.

Steps:

1. Install fresh Bika LIMS Evo
2. Install Demo Data
3. Go to Happy Hills
4. Create new AR and add some results
5. Go back to Happy Hills Client
6. Click on the AR in the listing
7. Click Pepublish button

<img width="619" alt="prepublish" src="https://user-images.githubusercontent.com/713193/33342807-a36536c0-d483-11e7-8046-6462d2d65bbe.png">

<img width="1179" alt="404" src="https://user-images.githubusercontent.com/713193/33342864-c080fe74-d483-11e7-9f63-407de2287807.png">

**Comment by ramonski** [comment]
IMO the request parameter `items` need to be called `uids`

**Comment by ramonski** [comment]
Registering the `publish` view for `IClient` raises the following error:

```
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module bika.lims.browser.analysisrequest.publish, line 116, in __call__
  Module Products.Five.browser.pagetemplatefile, line 125, in __call__
  Module Products.Five.browser.pagetemplatefile, line 59, in __call__
  Module zope.pagetemplate.pagetemplate, line 132, in pt_render
  Module five.pt.engine, line 98, in __call__
  Module z3c.pt.pagetemplate, line 158, in render
  Module chameleon.zpt.template, line 297, in render
  Module chameleon.template, line 191, in render
  Module chameleon.template, line 171, in render
  Module edb213b2a9b73af798b80633032a88ab.py, line 1020, in render
  Module bika.lims.browser.analysisrequest.publish, line 157, in getAnalysisRequest
  Module bika.lims.browser.analysisrequest.publish, line 752, in __call__
  Module bika.lims.browser.analysisrequest.publish, line 915, in _ar_data
AttributeError: getClientOrderNumber

 - Expression: "s python:('ar_publish_body singlear %s' % ('ar-invalid' if hasattr(view.getAnalysisRequestObj(),'isInvalid') and view.getAnalysisRequestObj().isInvalid() else ('ar-provisional' if view.getAnalysisRequest()['prepublish']==True else '')"
 - Filename:   ... ser/analysisrequest/templates/analysisrequest_publish.pt
 - Location:   (line 251: col 32)
 - Source:     ... s python:('ar_publish_body singlear %s' % ('ar-invalid' if hasattr(view.getAnalysisRequestObj(),'isInvalid') and view.getAnalysisRequestObj().isInvalid() else ('ar-provisional' if view.getAnalysisRequest()['prepublish']==True else '') ...
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 - Arguments:  default: <object - at 0x107130c40>
               repeat: {...} (0)
               template: <ViewPageTemplateFile - at 0x112c2ac50>
               views: <ViewMapper - at 0x112960a10>
               modules: <instance - at 0x1080df170>
               args: <tuple - at 0x1070da050>
               here: <ImplicitAcquisitionWrapper client-1 at 0x10e5b9a00>
               portal: <ImplicitAcquisitionWrapper senaite at 0x110578eb0>
               user: <ImplicitAcquisitionWrapper - at 0x10e5b9b90>
               nothing: <NoneType - at 0x107048ef8>
               plone_view: <Plone plone at 0x1127ea110>
               container: <ImplicitAcquisitionWrapper client-1 at 0x10e5b9a00>
               i: 0
               request: <instance - at 0x112826170>
               wrapped_repeat: <SafeMapping - at 0x10e5da890>
               portal_url: http://localhost:8080/senaite
               traverse_subpath: <list - at 0x1128184d0>
               loop: {...} (3)
               context: <ImplicitAcquisitionWrapper client-1 at 0x10e5b9a00>
               view: <AnalysisRequestPublishView publish at 0x112c2a050>
               portal_state: <PortalState plone_portal_state at 0x1127ea8d0>
               translate: <function translate at 0x113677050>
               root: <ImplicitAcquisitionWrapper Zope at 0x10f4a63c0>
               options: {...} (0)
               target_language: <NoneType - at 0x107048ef8>
```

**Comment by ramonski** [comment]
Not sure why the `referer` is used here to calculate the destination URL:
https://github.com/senaite/bika.lims/blob/master/bika/lims/browser/client/workflow.py#L195

Clicking on the "Analysisrequests" tab and then selecting an AR checkbox and clicking the prepublish button constructs then the following URL:
http://localhost:8080/senaite/clients/client-1/analysisrequests/publish?items=c3f684b88f594ce38a427e3baeb7bf7e

Where `analysisrequests` is obviously the name of the View
