### ISSUE TITLE
Applying a WS template which references a Duplicate raises an Error

### ISSUE THREAD

**Issue by ramonski** [senaite/bika.lims#448]
## Steps to reproduce

- Install Demo Data and edit the "Hardness" WS Template at /bika_setup/bika_worksheettemplates/worksheettemplate-1
- Add a duplicate and reference it to Position 2
- Add a new AR for Happy Hills
- Add Analyses of one Position
- Apply the WS template

## Current behavior

Traceback occurs

## Expected behavior

Applying an invalid template fails gracefully

## Traceback

```
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module bika.lims.browser.worksheet.views.add_analyses, line 121, in __call__
  Module bika.lims.content.worksheet, line 560, in applyWorksheetTemplate
  Module bika.lims.content.worksheet, line 416, in addDuplicateAnalyses
AttributeError: getSample
```

## Screenshot (optional)

<img width="926" alt="hardness_ _bika_und_senaite_lobby_-_gitter" src="https://user-images.githubusercontent.com/713193/33657153-ab537572-da78-11e7-8dfe-6810ebb4d5e1.png">

<img width="1154" alt="ws" src="https://user-images.githubusercontent.com/713193/33657002-3a8ed660-da78-11e7-9015-e40919d0a1c4.png">

<img width="930" alt="add-duplicate" src="https://user-images.githubusercontent.com/713193/33657031-53300fae-da78-11e7-98ef-1215a22bb1f6.png">

<img width="1154" alt="duplicate" src="https://user-images.githubusercontent.com/713193/33657065-6bfcbd20-da78-11e7-9fe1-08fc82a588d6.png">

<img width="922" alt="apply-template" src="https://user-images.githubusercontent.com/713193/33657294-28d8e338-da79-11e7-883b-8bc7acdab58b.png">

<img width="756" alt="traceback" src="https://user-images.githubusercontent.com/713193/33657322-3c350fb0-da79-11e7-9eb8-fbbb3554f8bd.png">

**Comment by xispa** [comment]
The problem here is that you are telling the system to duplicate, in position 2, the analysis located in position 2 ("Dup of" column).... that is itself!.

This should be fixed in the WS Template Layout view. I suggest the lists displayed in column "Dup of" to not display 1) their own position and 2) other positions that already have a duplicate assigned (to prevent the creation of a duplicate from a duplicate).

**Comment by ramonski** [comment]
I don't think that can be done in the WS template view, because the template does not know the setup of the WS it will be applied. In my example, I created the duplicate in the WS itself and applied the template afterwards. In any case, we need to avoid ending up in a Traceback.

**Comment by xispa** [comment]
I think that applying a WS Template once the Worksheet has already been created should not be possible. The WS Template is meant to be useful in WS creation time.

In any case, the way you defined your WS Template is not correct and either if you use that WS Template when creating the WS, I am confident you'll receive an error. There is a circular problem there: you define a duplicate at position 2 from the analysis that is in position 2.... system will never be able to deal with this conflict!

If js validation is out of the scope, then I suggest to validate the form when submitted to prevent this kind of conflicts, abort the submission and display a portal message like "Circular conflict in position 2".

**Comment by xispa** [comment]
My wrong, your WS Template is perfectly correct... forget the 2nd and 3nd pharagraphs from my prev comment. The first is still valid imo
