### ISSUE TITLE
Cannot select Analysis Specification in Analysis Request Add form if Sample Type is selected

### ISSUE THREAD

**Issue by xispa** [senaite/bika.lims#482]
## Steps to reproduce

1. Create a Sample Type "Lake Water".
1. Create an Analysis Specification "Lake Water Specs": set the sample type to "Lake Water" and assign some Analyses with their valid ranges.
1. Open Analysis Request Add Form for any given client.
1. Choose the Sample Type "Lake Water"
1. No specifications are listed for selection in "Analysis Specification" field.

## Current behavior

Analyses Specification not populated with available Analysis Specs when a Sample Type is previously selected. All Analysis Specifications are listed if no Sample Type was not previously selected.

## Expected behavior

Analysis Specifications that match with the selected Sample Type selected are displayed for their selection. If no Sample Type is selected, rather an Analysis Specification, the Sample Type field is filled automatically.

## Screenshot (optional)

![no_specs](https://user-images.githubusercontent.com/832627/34227139-711c9096-e5cc-11e7-992f-ed44d7d03b48.png)

**Comment by ramonski** [comment]
Related to https://github.com/senaite/bika.lims/issues/443
