### ISSUE TITLE
Cannot save attachments to Worksheets

### ISSUE THREAD

**Issue by lemoene** [senaite/bika.lims#501]
## Steps to reproduce

Navigate to an Open WS and attempt to upload an image as an attachment to it

## Current behavior

The Attachment widget seems to be in good order except for not offering me and Analysis (position) drop-down,  enter a valid position, then save the attachment

![image](https://user-images.githubusercontent.com/1196034/34421098-ea7a1cb6-ec15-11e7-82e9-3955a1633b19.png)

When the page refreshes, the attachment was not saved

## Expected behavior

The **_Analysis_** tag is misleading, best be retitled _Position_

When the user clicks it, a drop down of all the assigned Worksheet positions to which the attachment should be loaded

![image](https://user-images.githubusercontent.com/1196034/34421171-68958a18-ec16-11e7-834b-e08210481163.png)

I also have a feeling the two options _Position_ and _All Analyses of Service_ must be mutually exclusive

When the attachment is save, it should actually save

**Comment by ramonski** [comment]
Happens only in the bootstrap UI of `senaite.lims`

**Comment by ramonski** [comment]
Also affects `senaite.core`. After clicking the "Add2 button, the attachment is not applied

**Comment by ramonski** [comment]
The missing reference browser widget was fixed in https://github.com/senaite/senaite.lims/pull/51.
