### ISSUE TITLE
List of Analyses Services is not properly filtered by state

### ISSUE THREAD

**Issue by lemoene** [senaite/bika.lims#510]
## Steps to reproduce

I navigated to /bika_setup/bika_analysisservices/ and _de-activated_ Calcium from the Metals category and navigated among All, Active and Dormant listings

## Current behavior

All three filters seem to show the same 'Active' list, I cannot find Calcium back

![image](https://user-images.githubusercontent.com/1196034/34416875-4182ce80-ebfe-11e7-9e63-f918a9c5f06b.png)

![image](https://user-images.githubusercontent.com/1196034/34416903-65dc1700-ebfe-11e7-95c0-0a79ba0c8bac.png)

![image](https://user-images.githubusercontent.com/1196034/34416952-a1834544-ebfe-11e7-84e7-30ac2d2e4628.png)

## Expected behavior

As per screenshot annotation above

**Comment by lemoene** [comment]
Probably related:

The _Cancelled_ Calcium was successfully removed from the Profile it appeared on, but when the Profile is used, it gets added to the AR (even shaded as Cancelled:-)

![image](https://user-images.githubusercontent.com/1196034/34446913-ea377e92-ece7-11e7-9265-cba16d309a70.png)

![image](https://user-images.githubusercontent.com/1196034/34446970-4d88c9ec-ece8-11e7-8caa-7b6b7ff66215.png)

**Comment by xispa** [comment]
Please, open a new issue for this Profile + Inactive service bad behavior, cause this is not related with the original issue.
