### ISSUE TITLE
Bulk AR Imports missing

### ISSUE THREAD

**Issue by lemoene** [senaite/bika.lims#515]
## Steps to reproduce

Navigate to a Client

## Current behavior

The Imports menu item is missing

![image](https://user-images.githubusercontent.com/1196034/34447229-b4996734-ecea-11e7-9af5-855100cb0154.png)

## Expected behavior

![image](https://user-images.githubusercontent.com/1196034/34447266-f3b271a4-ecea-11e7-8cb1-4e2890162188.png)

**Comment by xispa** [comment]
This functionality should be coded in a separate add-on. Nevertheless, remember that Pull Requests are always welcome.

**Comment by lemoene** [comment]
For sure, we'll get to that. But was this function simply removed?  Key for Bika Water and a few other clients. That is why nobody gave me a straight answer... 

The issue should stay open as a feature request

**Comment by ramonski** [comment]
Afaik this functionality was never touched and appears on my screen as usual:

<img width="1374" alt="happy_hills_ _senaite" src="https://user-images.githubusercontent.com/713193/34461604-8567c2d6-ee2e-11e7-8e06-0d47e9abf7df.png">

However, I want to remove that or do it with the new AR Add form

**Comment by ramonski** [comment]
Maybe another weird permission setting that needs to be fixed:

<img width="600" alt="client_xml" src="https://user-images.githubusercontent.com/713193/34461623-08b36244-ee2f-11e7-8073-188f007f0259.png">

**Comment by xispa** [comment]
Might be related: https://github.com/senaite/bika.lims/pull/356
