### ISSUE TITLE
Assigned Icon on AR Lists.

### ISSUE THREAD

**Issue by lemoene** [senaite/bika.lims#520]
A potential performance issue (perhaps, 'All An Assigned' Boolean can be carried with ARs?) but it is currently difficult for lab managers to catch An falling through the cracks before late An Alert happens. We are missing a big potential pain point here

## Steps to reproduce

A manager navigates to the AR lists looking for unassigned ARs -he/she clicks the 'Unsassigned' icon, 

## Current behavior

and gets to see a cluttered list, they'd generally only be interested in _Received_ and _Due_ ARs

![image](https://user-images.githubusercontent.com/1196034/34453647-4505400a-ed62-11e7-9117-9f0d1ea474e1.png)

## Expected behavior

Please add option to include a column showing the _Assigned_ icon next to ARs _(Due, Received)_
Would _Unassigned_ be better? Positive imprinting... but in this case they Are looking for unassigned ARs almost always.
 
Maybe there is an easier way, exclude _To be verified, Verified and Published_ ARs from the Unassigned Filter?. I think we used an extra column in earlier versions.

![image](https://user-images.githubusercontent.com/1196034/34453730-efe48606-ed63-11e7-85e6-4ae7034fff57.png)

or 

![image](https://user-images.githubusercontent.com/1196034/34453743-74abefaa-ed64-11e7-89fc-15abba22467d.png)

**Comment by ramonski** [comment]
Please do not add feature requests to this tracker, unless you assign them directly to yourself and submit a PR afterwards. Thanks.

**Comment by lemoene** [comment]
Didn't duplication cost everybody enough already?

**Comment by ramonski** [comment]
Issues like this have the tendency to remain open forever and thus, will cost us all much more time falling over it again and again.

**Comment by lemoene** [comment]
That way you'll be losing valuable reports + pissing on a lot of innocent and enthusiastic prospects? All can be positively harnessed - the 'Student' label in Jira came in handy for that. 

I cannot do assigning here

**Comment by lemoene** [comment]
This particular issue is not low priority but Key to labs to not lose Analyses through the cracks
